batch_size: 32
system_prompt: null
model_name: "meta-llama/Llama-3.1-8B-Instruct"
initial_answers_args_name: q1e3_fw
probe_responses_args_name: q1e3_fw
probe_analysis_args_name: q1e3_fw
questions_data_name: "questions_1000_all"
question_instruction: "Answer with one word."
probe_file_name: "probes_with_ten_words_reduced"
probe_response_type: "five_words"
prompt_idx: 8
samples_per_context_length: 64
context_lengths: [0, 1, 2, 5, 10, 15, 20, 25, 30]
excluded_probe_types: []  # Already reduced!
icl_sorting_key: effect_size
