batch_size: 32
system_prompt: null
question_instruction: "Answer with 30 words."
questions_data_name: "dangerous_advice"
model_name: "meta-llama/Llama-3.1-8B-Instruct"
prompt_idx: 9

num_initial_generation_samples: 32
top_p: 0.9
temperature: 0.6
