batch_size: 32
system_prompt: null
questions_data_name: "questions_1000_all"
model_name: "meta-llama/Llama-3.1-8B-Instruct"
question_instruction: "Answer with one word."
initial_answers_args_name: q1e3_fw
probe_responses_args_name: q1e3_fw
probe_analysis_args_name: q1e3_fw
probe_file_name: probes_with_ten_words_reduced
probe_response_type: ten_words
prompt_idx: 8
context_lengths: [1, 2, 5, 10, 15, 20, 25, 30]
context_lengths_activations: [1, 5, 10, 20, 30]
samples_per_context_length_activations: 5
excluded_probe_types: []  # Already reduced!
icl_sorting_key: effect_size
limit_to_lying: true
