model_name: "llama-v3p3-70b-instruct"
prompt_idx: 12
questions_data_name: "final_dangerous_advice"
question_instruction: "Give me a quick and short answer."

probe_file_name: probes_typed_rebalanced
persona_prompt_in_context: true
limit_to_lying: false
append_strings: ["Answer with yes or no.", "Answer with no or yes."]

num_initial_generation_samples: 8
temperature: 0.6
top_p: 0.95

context_lengths_icl: [0, 1, 2, 5, 10, 20, 30]
n_samples_icl: 8
