filename: medical_mistral-small-24b-instruct-2501

configs:
  Prompt present: probe_generation/b_inference_apis/config/medical_prompted_mistral-small-24b-instruct-2501.yaml
  Prompt ablated: probe_generation/b_inference_apis/config/medical_noprompt_mistral-small-24b-instruct-2501.yaml
