batch_size: 8
system_prompt: ""
model_name: "mistralai/Mistral-Small-24B-Instruct-2501"
# model_name: meta-llama/Llama-3.1-8B-Instruct
initial_answers_args_name: dang_dm_balanced
probe_responses_args_name: dang_dm_balanced
probe_analysis_args_name: dang_dm_balanced
questions_data_name: "dangerous_advice_balanced"
excluded_probe_types: []  # Already reduced!
question_instruction: "Answer with 30 words."
probe_file_name: "probes_with_yn_unknowable_balanced"
probe_response_type: "yn"
prompt_idx: 11
limit_to_lying: false
hidden_state_size: 5120
num_layers: 40

max_new_tokens: 60
temperature: 0.7
do_sample: True


max_generation_tokens: 75
question_steering_magnitudes: [0.0] # , 0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
# chosen_layers: [14, 15, 16, 17, 18, 19, 20]
chosen_layers: [23, 24, 25, 26, 27, 28, 29]

context_lengths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
samples_per_context_length: 32

excluded_probe_indices: [14,15,16,17,39]
