batch_size: 32
system_prompt: null
questions_data_name: "dangerous_advice"
model_name: "meta-llama/Llama-3.1-8B-Instruct"
question_instruction: "Answer with 30 words."
initial_answers_args_name: dang
probe_responses_args_name: dang_yn
probe_analysis_args_name: dang_yn
probe_file_name: "probes_with_yn_reduced"
probe_response_type: yn
prompt_idx: 9
context_lengths: [0, 1, 2, 5, 10, 15, 20, 30]
context_lengths_activations: [1, 5, 10, 20, 30]
samples_per_context_length_activations: 5
excluded_probe_types: []  # Already reduced!
icl_sorting_key: effect_size
limit_to_lying: false

