system_prompt: ""
model_name: "mistralai/Mistral-Small-24B-Instruct-2501"
initial_answers_args_name: dang_dm
questions_data_name: "dangerous_advice"
question_instruction: "Answer with 30 words."
probe_file_name: "probes_with_yn_unknowable"
probe_response_type: "yn"
prompt_idx: 10
limit_to_lying: false
batch_size: 4
